# Generated by Django 4.2.3 on 2023-08-17 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_consultorio_options_alter_paciente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['estado']},
        ),
    ]
