# Generated by Django 4.2.3 on 2023-08-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultorio',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['apellido']},
        ),
        migrations.AlterModelOptions(
            name='profesional',
            options={'ordering': ['apellido'], 'verbose_name': 'Profesional', 'verbose_name_plural': 'Profesionales'},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['dia']},
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='diagnostico',
            new_name='estado',
        ),
    ]
